baseURL: https://dablog.pages.dev/
paginate: 10
theme: charlolamode

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  es:
    contentDir: content/es
    disabled: false
    languageCode: es-ES
    languageDirection: ltr
    languageName: ğŸ‡ªğŸ‡¸
    params:
      subtitle: ideas, tutoriales y cosas sin sentido
    title: rooyca
    weight: 2

    menu:
        main:
            - name: ArtÃ­culos
              url: /articulos/
              weight: 10
            - name: Proyectos
              url: /proyectos/
              weight: 20
    params:
      profileMode:
          enabled: true
          title: rooyca
          description: "
            ğŸ§”ğŸ» / ğŸ‡¨ğŸ‡´


            Â« Aprendiz de todo, maestro de nada Â»


            [ ğŸ“š Dilettante ] â€¢ [ ğŸ¶ MelÃ³mano ]"
          nowPlaying: "https://img.shields.io/endpoint?url=https://lastfm-last-played.biancarosa.com.br/rooyca/latest-song?format=shields.io&style=flat-square&logo=spotify&label=Now Playing&labelColor=black&color=grey"
          imageUrl: "https://avatars.githubusercontent.com/u/42101257?v=4"
          imageTitle: profile
          
          buttons:
              - name: Portafolio
                url: https://rooyca.github.io/

  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: ğŸ‡ºğŸ‡¸
    params:
      subtitle: ideas, tutorials and nonsense
    title: rooyca
    weight: 1

    menu:
        main:
            - name: Articles
              url: /articles/
              weight: 10
            - name: Projects
              url: /projects/
              weight: 20

    params:
      profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: rooyca
        description: "
          ğŸ§”ğŸ» / ğŸ‡¨ğŸ‡´


          Â« Jack of all trades, master of none Â»


          [ ğŸ“š Dilettante ] â€¢ [ ğŸ¶ Melomaniac ] "
        nowPlaying: "https://img.shields.io/endpoint?url=https://lastfm-last-played.biancarosa.com.br/rooyca/latest-song?format=shields.io&style=flat-square&logo=spotify&label=Now Playing&labelColor=black&color=grey"
        imageUrl: "https://avatars.githubusercontent.com/u/42101257?v=4"
        imageTitle: profile

        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Portfolio
              url: https://rooyca.github.io/

params:
    author: rooyca

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowWordCount: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    DateFormat: "2 Jan 2006"
    hideAuthor: true
    #comments: true
    disableAckee: true
    ShowRssButtonInSectionTermList: true
    description: "This blog's purpose is to share things I've learned, projects I've done and, in general, things that I find interesting."

    keywords: 
      - "ideas"
      - "tutorials"
      - "projects"
      - "programming"
      - "technology"
      - "development"
      - "blogging"
      - "notes"

    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/rooyca"
        - name: twitter
          url: "https://twitter.com/rooycaa"
        - name: telegram
          url: "https://t.me/yarocc"
        - name: mastodon
          url: "https://mas.to/@rooyca"
        #- name: keybase
        #  url: "https://keybase.io/rooyca"
        - name: hackerrank
          url: "https://www.hackerrank.com/rooyca"
        #- name: kofi
        #  url: "https://ko-fi.com/rooyca"
        - name: pgpkey
          url: "https://pgp.rooyca.workers.dev/?fp=0CCBAE3240C1522155278DE4CB666DEC17F3A6D5"
        - name: email
          url: "mailto:blog.png8n@slmail.me"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

copyright: Â© 2024
